library(gdata)
library(ggplot2)
data1 <- read.csv("~/Dropbox/nescent_extinction_map/Final data/Modern and PaleoDB ranges FINAL 2.0.csv",header = TRUE,stringsAsFactors = FALSE)
Modern <- drop.levels(subset(data1,data1$Interval_Name=="Modern"))
Plio_Pleistocene <- drop.levels(subset(data1,data1$Interval_Name=="Plio-Pleistocene"))

Modern <- data.frame(Modern$genus,Modern$lat.range)
colnames(Modern) <- c("genus","occupancy")
Plio_Pleistocene <- data.frame(Plio_Pleistocene$genus,Plio_Pleistocene$lat.range)
colnames(Plio_Pleistocene) <- c("genus","occupancy")
plotdata <- merge(Modern,Plio_Pleistocene,by="genus")
colnames(plotdata) <- c("genus","Modern_occupancy","Plio_Pleistocene_occupancy")
p <- ggplot(plotdata,aes(log(Modern_occupancy),log(Plio_Pleistocene_occupancy))) +geom_point(pch=1)
p + geom_abline() 

cor(plotdata$Modern_occupancy,plotdata$Plio_Pleistocene_occupancy,method="spearman")
